# Generated by Django 4.1.5 on 2023-03-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_add_teacher_details_is_head_of_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.add_teacher_details')),
            ],
        ),
    ]
