# Generated by Django 4.1.5 on 2023-03-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_login',
            options={'verbose_name_plural': 'Teacher Login'},
        ),
        migrations.AlterModelTable(
            name='teacher_login',
            table='Teacher Login',
        ),
    ]
