# Generated by Django 4.1.5 on 2023-03-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Semester_Details', '0001_initial'),
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone_number', models.CharField(max_length=20)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone_number', models.CharField(max_length=20)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('sslc_percents', models.FloatField(max_length=10)),
                ('plus_two_percent', models.FloatField(max_length=10)),
                ('extracurricular_activities', models.CharField(max_length=200)),
                ('register_number', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semester_Details.semester')),
            ],
            options={
                'verbose_name_plural': 'Student_Details',
            },
        ),
    ]
