# Generated by Django 4.1.5 on 2023-03-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student Details'},
        ),
    ]
