# Generated by Django 4.1.5 on 2023-03-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Semester_Details', '0001_initial'),
        ('Department', '0001_initial'),
        ('Student', '0003_student_dob_alter_student_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('hour_one', models.IntegerField(default=1)),
                ('hour_two', models.IntegerField(default=1)),
                ('hour_three', models.IntegerField(default=1)),
                ('hour_four', models.IntegerField(default=1)),
                ('hour_five', models.IntegerField(default=1)),
                ('hour_six', models.IntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semester_Details.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
