# Generated by Django 4.1.5 on 2023-04-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Semester_Details', '0001_initial'),
        ('Department', '0001_initial'),
        ('Student', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('subject_one', models.CharField(max_length=200)),
                ('subject_two', models.CharField(max_length=200)),
                ('subject_three', models.CharField(max_length=200)),
                ('subject_four', models.CharField(max_length=200)),
                ('subject_five', models.CharField(max_length=200)),
                ('subject_six', models.CharField(max_length=200)),
                ('mark_one', models.IntegerField()),
                ('mark_two', models.IntegerField()),
                ('mark_three', models.IntegerField()),
                ('mark_four', models.IntegerField()),
                ('mark_five', models.IntegerField()),
                ('mark_six', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Semester_Details.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'verbose_name_plural': 'Exam',
            },
        ),
    ]
