# Generated by Django 4.1.5 on 2023-04-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'verbose_name_plural': 'Student Login',
            },
        ),
    ]
