# Generated by Django 4.1.5 on 2023-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_student_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sslc_percents',
            new_name='sslc_percentage',
        ),
    ]
