# Generated by Django 4.1.5 on 2023-05-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_rename_sslc_percents_student_sslc_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='plus_two_percent',
            new_name='plus_two_percentage',
        ),
    ]
