# Generated by Django 4.1.5 on 2023-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_add_teacher_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_teacher_details',
            options={'verbose_name_plural': 'Teacher Details'},
        ),
        migrations.AlterField(
            model_name='add_teacher_details',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add_teacher_details',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
