# Generated by Django 4.1.5 on 2023-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_add_teacher_details_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_teacher_details',
            name='is_head_of_department',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='add_teacher_details',
            table='Teacher Details',
        ),
    ]
